<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SibylEarbuds.App</RootNamespace>
    <AssemblyName>SibylEarbudsManager</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SibylEarbuds.Core\SibylEarbuds.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Audio\*.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Images\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
